scheme: Muse
darkmode: false
motion:
  enable: true
  async: false

menu:
  home: / || fa fa-home
  中文: /zh-cn/ || fa fa-language
  English: /en/ || fa fa-language
  日本語: /ja/ || fa fa-language
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-people-pulling
  about: /about/ || fa fa-user

avatar:
  url: /images/avatar.gif
  rounded: true
  rotated: false

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

creative_commons:
  license: by-nc-sa
  sidebar: false
  post: true
  language: deed.zh

social:
  GitHub: https://github.com/ || fab fa-github
  RSS: /atom.xml || fa fa-rss

footer:
  since: 2026
  icon:
    name: fa fa-heart
    animated: false
    color: '#808080'
  copyright: true
  powered: true

sidebar:
  position: left
  display: always
  padding: 18
  offset: 12

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

copy_button:
  enable: true
  show_result: true
  style:

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: false

bookmark:
  enable: false

lazyload: false
pangu: false

comments:
  style: tabs
  active:
  storage: true
  lazyload: false
  nav:

waline:
  enable: false
  serverURL:
  placeholder: 请文明评论呀
  avatar: mm
  meta:
    - nick
    - link
  pageSize: 10
  lang: zh-CN
  visitor: false
  comment_count: false
  requiredFields: []
  reaction: false

